cudaV1:
	/usr/local/cuda-11.2/bin/nvcc matrix-mult-cuda-threads-v1.cu -o matrix-mult-cuda-threads-v1
	/usr/local/cuda-11.2/bin/nvprof ./matrix-mult-cuda-threads-v1
cudaV2:
	/usr/local/cuda-11.2/bin/nvcc matrix-mult-cuda-threads-v2.cu -o matrix-mult-cuda-threads-v2
	/usr/local/cuda-11.2/bin/nvprof ./matrix-mult-cuda-threads-v2
cudaV3:
	/usr/local/cuda-11.2/bin/nvcc matrix-mult-cuda-threads-v3.cu -o matrix-mult-cuda-threads-v3
	/usr/local/cuda-11.2/bin/nvprof ./matrix-mult-cuda-threads-v3
cleanV1:
	rm matrix-mult-cuda-threads-v1
cleanV2:
	rm matrix-mult-cuda-threads-v2
cleanV3:
	rm matrix-mult-cuda-threads-v3

